eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://192.168.10.188:8761/eureka/
server:
  port: 8762
spring:
  zipkin:
    base-url: http://192.168.10.188:9411
  application:
    name: service-hi